name: htlib
description: Project phần mềm quản lí thư viện Hàn Thuyên.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.2.2+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  exifdart:
    git:
      url: https://github.com/definev/exifdart.git
      ref: master
  animations: ^2.0.0
  barcode_image: ^2.0.0
  bloc: ^7.0.0
  cached_network_image: ^3.0.0
  cloud_firestore: ^1.0.3
  dartz: 0.10.0-nullsafety.1
  desktop_window: ^0.4.0
  diacritic: ^0.1.3
  diffutil_sliverlist: ^0.5.0
  dotted_border: 2.0.0-nullsafety.0
  excel: 2.0.0-null-safety
  file_picker: ^3.0.0
  filepicker_windows: ^2.0.0
  firebase: ^9.0.1
  firebase_auth: ^1.0.1
  firebase_core: ^1.0.2
  firebase_storage: ^8.0.1
  flex_color_scheme: ^2.1.0
  flutter_barcode_scanner: 2.0.0-nullsafety.0
  flutter_bloc: ^7.0.0
  flutter_icons:
    git:
      url: https://github.com/adarsh-technocrat/flutter-icons.git
      ref: master
  flutter_sticky_header:
    git:
      url: https://github.com/Femtopedia/flutter_sticky_header.git
      ref: master
  freezed_annotation: ^0.14.1
  get: ^4.1.1
  google_fonts: ^2.0.0
  hive: ^2.0.1
  hive_flutter: ^1.0.0
  image: ^3.0.2
  image_picker: null
  image_picker_for_web: null
  intl: ^0.17.0
  pattern_formatter: ^2.0.0
  pdf: ^3.1.0
  permission_handler: ^6.1.1
  printing: ^5.0.4
  textstyle_extensions: 2.0.0-nullsafety
  time: ^2.0.0
  universal_html: ^2.0.7
  url_launcher: ^6.0.3
  uuid: ^3.0.3

dependency_overrides:
  universal_html: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.13
  hive_generator: ^1.0.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  assets:
    - assets/images/
    - assets/fonts/Guanine.ttf
    - assets/fonts/Habano.ttf
    - assets/fonts/Hanzel.ttf
    - assets/fonts/VarelaRound-Regular.ttf
    - assets/fonts/OpenSans-Regular.ttf
    - assets/fonts/OpenSans-Bold.ttf
    - assets/fonts/Typold.ttf
    - assets/fonts/Roboto-Regular.ttf

  uses-material-design: true
  fonts:
    - family: Guanine
      fonts:
        - asset: assets/fonts/Guanine.ttf
    - family: Habano
      fonts:
        - asset: assets/fonts/Habano.ttf
    - family: Hanzel
      fonts:
        - asset: assets/fonts/Hanzel.ttf
