name: htlib
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  window_size:
    git:
      url: git://github.com/google/flutter-desktop-embedding.git
      path: plugins/window_size
  animations: ^1.1.2
  cloud_firestore: ^0.16.0
  cupertino_icons: ^1.0.1
  dartz: ^0.9.2
  diacritic: ^0.1.1
  excel: ^1.1.5
  file_picker: ^2.1.5+1
  filepicker_windows: ^1.0.0
  firebase_core: ^0.7.0
  firebase_storage: ^7.0.0
  flex_color_scheme: ^1.4.1
  flutter_barcode_scanner: ^1.0.2
  flutter_icons: ^1.1.0
  flutter_portal: ^0.3.0
  get: 3.24.0
  get_it: ^5.0.6
  google_fonts: ^1.1.1
  hive: ^1.4.4+1
  hive_flutter: ^0.3.1
  http: ^0.12.2
  icon_animator: ^0.0.4
  image_picker: ^0.6.7+21
  injectable: ^1.0.7
  intl: ^0.16.1
  loading_indicator: ^1.2.0
  path_provider: ^1.6.27
  permission_handler: ^5.0.1+1
  pluto_grid: ^1.0.0
  qr_flutter: ^3.2.0
  qrscan: ^0.2.21
  sized_context: ^0.2.1+1
  styled_widget: ^0.2.2
  textstyle_extensions: ^1.1.0
  time: ^1.4.0
  url_launcher: ^5.7.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.13
  hive_generator: ^0.8.2
  injectable_generator: ^1.0.7

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  assets:
    - assets/images/
    - aes.js
  uses-material-design: true
  fonts:
    - family: Quicksand
      fonts:
        - asset: assets/fonts/Quicksand-Light.ttf
          weight: 200
        - asset: assets/fonts/Quicksand-Regular.ttf
          weight: 400
        - asset: assets/fonts/Quicksand-SemiBold.ttf
          weight: 500
        - asset: assets/fonts/Quicksand-Medium.ttf
          weight: 600
        - asset: assets/fonts/Quicksand-Bold.ttf
          weight: 700

    - family: Comfortaa
      fonts:
        - asset: assets/fonts/Comfortaa-Light.ttf
          weight: 300
        - asset: assets/fonts/Comfortaa-Regular.ttf
          weight: 400
        - asset: assets/fonts/Comfortaa-SemiBold.ttf
          weight: 700
        - asset: assets/fonts/Comfortaa-Bold.ttf
          weight: 800

    - family: Fraunces
      fonts:
        - asset: assets/fonts/Fraunces_144pt-Light.ttf
          weight: 200
        - asset: assets/fonts/Fraunces_144pt-Regular.ttf
          weight: 400
        - asset: assets/fonts/Fraunces_144pt-SemiBold.ttf
          weight: 500
        - asset: assets/fonts/Fraunces_144pt-Bold.ttf
          weight: 600
        - asset: assets/fonts/Fraunces_144pt-Black.ttf
          weight: 700

    - family: OpenSansEmoji
      fonts:
        - asset: assets/fonts/OpenSansEmoji.ttf
