name: htlib
description: Project phần mềm quản lí thư viện Hàn Thuyên.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.9.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  exifdart:
    git:
      url: git://github.com/definev/exifdart
      ref: master
  animations: ^1.1.2
  bloc: ^6.1.1
  cached_network_image: ^2.5.0
  cloud_firestore: ^0.16.0
  dartz: ^0.9.2
  desktop_window: ^0.3.0
  diacritic: ^0.1.1
  diffutil_sliverlist: ^0.4.1
  dotted_border: ^1.0.7
  excel: ^1.1.5
  file_picker: ^2.1.6
  filepicker_windows: ^1.0.0
  firebase: null
  firebase_core: ^0.7.0
  firebase_storage: ^7.0.0
  flex_color_scheme: ^1.4.1
  flutter_barcode_scanner: ^1.0.2
  flutter_bloc: ^6.1.2
  flutter_chips_input: ^1.9.5
  flutter_icons: ^1.1.0
  flutter_sticky_header: ^0.5.0
  freezed_annotation: ^0.12.0
  get: ^3.25.4
  get_it: ^5.0.6
  google_fonts: ^1.1.1
  hive: ^1.4.4+1
  hive_flutter: ^0.3.1
  image_picker: null
  image_picker_for_web: null
  intl: ^0.17.0
  pattern_formatter: ^1.0.2
  pdf: null
  permission_handler: ^5.0.1+1
  printing: 
  scan_preview: ^1.0.2
  styled_widget: ^0.2.2
  textstyle_extensions: ^1.1.0
  universal_html: ^1.2.4
  url_launcher: ^5.7.10
  uuid: 

dependency_overrides:
  intl: ^0.17.0
  universal_io: 1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.13
  freezed: ^0.12.7
  hive_generator: ^0.8.2

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  assets:
    - assets/images/
    - assets/fonts/Guanine.ttf
    - assets/fonts/Habano.ttf
    - assets/fonts/Hanzel.ttf

  uses-material-design: true
  fonts:
    - family: Guanine
      fonts:
        - asset: assets/fonts/Guanine.ttf
    - family: Habano
      fonts:
        - asset: assets/fonts/Habano.ttf
    - family: Hanzel
      fonts:
        - asset: assets/fonts/Hanzel.ttf
